service: grupo-sillas-bot

provider:
  name: aws
  runtime: rust
plugins:
  - serverless-rust
package:
  individually: true

custom:
  rust:
    dockerless: true

functions:
  test:
    handler: grupo-sillas-bot
    environment:
      DISCORD_BOT_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
    events:
      - httpApi: 'POST /interaction'